### ISSUE TITLE
Where can i get the training dataset ?

### ISSUE THREAD

**Issue by duongnv0499** [mdv3101/CDeCNet#1]
Hi, I'd like to re-train your model with IIIT-AR-13K dataset. Do you mind sharing the link to download it?  Thank you in advance.

**Comment by madhav1ag** [comment]
Hi @duongnv0499 ,
You can download the IIIT-AR-13K dataset from the following link http://cvit.iiit.ac.in/usodi/img/projects/detection/iiit-ar-13/dataset/IIIT-AR-13K_dataset.zip

**Comment by duongnv0499** [comment]
thanks, is the dataset in VOC format ? I downloaded it and saw the xml file ? can you please help me convert it to coco format ?

**Comment by madhav1ag** [comment]
Please refer to the IIIT-AR-13K paper for information regarding the dataset. You can find the paper at following [link](http://cdn.iiit.ac.in/cdn/cvit.iiit.ac.in/usodi/img/projects/detection/iiit-ar-13/pdf/IIIT-AR-13K.pdf)

**Comment by arushijain45** [comment]
Can you please share the sample of coco format of IIIT-AR-13k dataset mentioning the required attributes for annotations field.
I am using following json but seems to be incomplete:
```
{
"images": [{"file_name": "dataset/coco/sample/train_images/ar_alphabet_2004_eng_0.jpg", "width": 850, "height": 1100, "id": 1}, ... ],
"annotations": [{"bbox": [101.0, 210.0, 748.0, 384.0], "category_id": 1, "image_id": 1, "id": 10, "area": 112578, "segmentation": []}, ... ],
"categories": [{"id": 1, "name": "table"}, ... ]
}
```

**Comment by madhav1ag** [comment]
@arushijain45 
We have uploaded a sample json file in coco format for your reference: [link](https://github.com/mdv3101/CDeCNet/blob/master/sample/coco_sample.json)

**Comment by arushijain45** [comment]
Thank you @mdv3101
