### ISSUE TITLE
CPU Support for Deformable-CNN

### ISSUE THREAD

**Issue by prnan4** [mdv3101/CDeCNet#10]
Hi,

I was wondering if you could provide support to run the inferencing alone on CPU? Currently Deformable CNNs are supported only in CUDA OPS and do not have a vanilla torch implementation. Do you plan to implement this in the future?

Thank you, 
Nandhinee

**Comment by madhav1ag** [comment]
Hi @prnan4,
We don't have any immediate plan to provide CPU support. 

Thanks
