### ISSUE TITLE
Docker container not working

### ISSUE THREAD

**Issue by flix59** [mdv3101/CDeCNet#16]
I tried to use the docker container with the image_demo.py. 
Running the default docker container in the repo gives me the error, that mmcv is missing.  
So I added:
```
RUN pip install mmcv-full==latest+torch1.5.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html
```
from https://github.com/open-mmlab/mmdetection/blob/master/docker/Dockerfile.
when running the demo i get: 
```
  File "demo/image_demo.py", line 26, in <module>
    main()
  File "demo/image_demo.py", line 18, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/mmdetection/mmdet/apis/inference.py", line 39, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "/mmdetection/mmdet/models/builder.py", line 77, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/mmdetection/mmdet/models/builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 182, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "CascadeRCNN: 'DB_ResNeXt is not in the backbone registry' "
```
I saw #11 but I thought the docker container installs everything properly for me.
Any suggestions on how I should change the dockerfile to get the dependencies installed properly?

**Comment by madhav1ag** [comment]
Hi @flix59 ,
We don't provide support for Docker, so I won't be able to help you much.

Looking at the error, it seems that the docker has installed mmdetection official repo, instead of CDeCNet.

Thanks
