### ISSUE TITLE
Unable to run  image_demo.py on downloaded PubLayNet model

### ISSUE THREAD

**Issue by amoghaimaging** [mdv3101/CDeCNet#17]
Appreciate greatly the great work done by you guys.
I am trying to run image_demo.py on the PubLayNet downloaded from the link provided. The result does not have any bounding box for table. I am getting the following messages in the console:

/usr/local/lib/python3.7/dist-packages/mmcv/utils/misc.py:304: UserWarning: "out_size" is deprecated in `RoIAlign.__init__`, please use "output_size" instead
  f'"{src_arg_name}" is deprecated in '
/usr/local/lib/python3.7/dist-packages/mmcv/utils/misc.py:304: UserWarning: "sample_num" is deprecated in `RoIAlign.__init__`, please use "sampling_ratio" instead
  f'"{src_arg_name}" is deprecated in '
_**The model and loaded state dict do not match exactly**

size mismatch for backbone.layer1.0.conv1.weight: copying a param with shape torch.Size([128, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 1, 1]).
size mismatch for backbone.layer1.0.bn1.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64])._

Appreciate your help with this issue.

**Comment by madhav1ag** [comment]
Hi,
Can you share the image on which you are running the demo?

**Comment by Darrenonly** [comment]
![image](https://user-images.githubusercontent.com/43534947/116667873-41ab4580-a9cf-11eb-81e7-efe083a6d5df.png)
Appreciate your help with this issue.

**Comment by madhav1ag** [comment]
Hi @Darrenonly,
It looks like you are not using GPU for running the code. CDeCNet is not compatible with CPU only machines
