### ISSUE TITLE
"ImportError: DLL load failed: The specified procedure could not be found." 

### ISSUE THREAD

**Issue by shriyakak** [mdv3101/CDeCNet#2]
I am getting error "ImportError: DLL load failed: The specified procedure could not be found."-- referring to deform_conv_ext.cp37-win_amd64.pyd file from deform_layer. I am trying to run the repo on windows 10. I have followed the steps mentioned in readme. Could you please suggest how to run this on windows 10.

**Comment by madhav1ag** [comment]
Hi @shriyakak , 
The mmdetection framework currently supports Linux and MacOS only. You can refer to  [install.md](https://github.com/mdv3101/CDeCNet/blob/master/docs/install.md#requirements) 
Thanks
