### ISSUE TITLE
Dataset formation

### ISSUE THREAD

**Issue by PriyankaJain-1998** [mdv3101/CDeCNet#20]
![image](https://user-images.githubusercontent.com/58905207/126953295-2f76df5d-056d-4632-8d07-8fd907456026.png)
Can you please explain this part of the readme file else can add the data folder or link from where we can download it.

**Comment by madhav1ag** [comment]
This is the directory structure of the dataset. You can use any dataset (like publically available ICDAR, UNLV, etc. or any private dataset) and put them in the given directory structure. Annotation folder contains a json file (eg: [json](https://github.com/mdv3101/CDeCNet/blob/master/sample/coco_sample.json)), train2014 contains training images and val2014 contains Validation/Testing images. They follow standard MS-Coco structure.

**Comment by PriyankaJain-1998** [comment]
what about logs folder?
What exactly is expected to be inside that?

**Comment by madhav1ag** [comment]
Log folder contains the checkpoint/weight file. When you are training a model, checkpoint files will be stored in log folder.

**Comment by PriyankaJain-1998** [comment]
Can you please share the link of any particular dataset which I can use here and have the same folders formation as required.

**Comment by madhav1ag** [comment]
@PriyankaJain-1998 Kindly go through the paper to find details about the dataset. These datasets may not have the exact directory structure, so you might need to change accordingly.
You can check IIIT-AR-13K dataset for reference ([link](http://cvit.iiit.ac.in/usodi/iiitar13k.php)). (Note that this dataset has 5 classes, so you need to filter out only tables).
