### ISSUE TITLE
Issues with library dependency (datascience , coverage, foliam.) during installation 

### ISSUE THREAD

**Issue by Isunny-pixel** [mdv3101/CDeCNet#21]
I am getting these issues while instaling: I have issues with coverage. if I put it as 4.4 there's error to make it 3.7.1 if I do that It suggest me to go back

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
datascience 0.10.6 requires coverage==3.7.1, but you have coverage 4.4 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.10.1 which is incompatible.
coveralls 0.5 requires coverage<3.999,>=3.6, but you have coverage 4.4 which is incompatible.`

if I manually change it, 

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pytest-cov 2.9.0 requires coverage>=4.4, but you have coverage 3.7.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.10.1 which is incompatible.`

can someone help me resolve these dependency issues?

**Comment by madhav1ag** [comment]
@Isunny-pixel We are unable to reproduce your dependency error. The installation is working fine at our end.
