### ISSUE TITLE
Training Issue 

### ISSUE THREAD

**Issue by PriyankaJain-1998** [mdv3101/CDeCNet#22]
![image](https://user-images.githubusercontent.com/58905207/128337328-ed0b71ee-18aa-45d3-827b-9cfa6067ed4f.png)
Please help. Following the same guidelines as suggested

**Comment by madhav1ag** [comment]
Hi @PriyankaJain-1998,
This PermissionError is related to your local machine. It has nothing to do with CDeCNet. Kindly check the permissions/access writes to your local directories.
