### ISSUE TITLE
KeyError: 'meta'

### ISSUE THREAD

**Issue by vineethbabu** [mdv3101/CDeCNet#23]
Hi @mdv3101, thanks for the awesome project.
I am trying to run inference with the pre-trained model but i am getting the following error:
My environment is colab notebook and I followed steps from install.md
```
Traceback (most recent call last):
  File "/content/CDeCNet/demo/image_demo.py", line 28, in <module>
    main()
  File "/content/CDeCNet/demo/image_demo.py", line 20, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/content/CDeCNet/mmdet/apis/inference.py", line 36, in init_detector
    if 'CLASSES' in checkpoint['meta']:
KeyError: 'meta' 
```

my command is:
```
!python demo/image_demo.py <image> configs/dcn/db_cascade_mask_rcnn_x101_fpn_dconv_c3-c5_1x_coco.py \
    /gdrive/MyDrive/table_detection_model/db_cascade_mask_rcnn_x101_32x4d_fpn_dconv_c3-c5_1x_coco-e75f90c8.pth \
    --score-thr 0.95 --output-img 'output_demo.jpg'
```
in the installation step i tried both pip and setup install, but both are giving me same error. is there a mismatch between my pretrain and config file. Thanks in advance.

**Comment by madhav1ag** [comment]
Hi @vineethbabu 
The checkpoint file 'db_cascade_mask_rcnn_x101_32x4d_fpn_dconv_c3-c5_1x_coco-e75f90c8.pth' is not for detecting tables. This is trained on coco dataset and contains 80 classes.
To run inference, you need to download models given in [CDeCNet Results](https://github.com/mdv3101/CDeCNet#cdecnet-results) section. You can run inference from any of the models.

**Comment by vineethbabu** [comment]
Thanks @mdv3101, its working now.
