### ISSUE TITLE
Extend model for table structutre recognition

### ISSUE THREAD

**Issue by Atul997** [mdv3101/CDeCNet#3]
Can we use checkpoints for training the model for cell and table detection at the same time?

**Comment by madhav1ag** [comment]
The current framework and checkpoint files are for table detection. You need to make some changes for cell detection training like annotations,  classes, few other changes in code etc. After that, you can use transfer learning or train a model from scratch to detect tables and cells simultaneously. 
PS: We haven't tried cell detection using CDeCNet.

**Comment by Atul997** [comment]
Thanks.
Are you guys planning to do so? I have made some changes to code and classes and started the training. I will let you know!

**Comment by madhav1ag** [comment]
We are working on cell detection but haven't tried CDeCNet for it. Do share the results, if they are intriguing than we will give it a shot.
Thanks

**Comment by kbrajwani** [comment]
Hey, thanks for such a great repo.
![cell detect](https://user-images.githubusercontent.com/29722986/104190474-03aef500-53d1-11eb-9f77-ea6f7bbb402c.png)

i was trying to apply your model for cell detection on this repo dataset(https://github.com/sachinraja13/TabStructNet) and got results as shown in the image. Can you tell me how can I improve this?

**Comment by madhav1ag** [comment]
Hi @kbrajwani 
You can tweak the hyper-parameters to make it more intensive for small objects (Cells in Table). It is an open area for research, you have to try different things.
