### ISSUE TITLE
No "demo" folder for image_demo.py

### ISSUE THREAD

**Issue by Atul997** [mdv3101/CDeCNet#4]
I didn't see any demo folder in the repo for a single image testing.

**Comment by madhav1ag** [comment]
Hi,
We haven't tested the scripts provided in 'demo' folder. You can try them at [mmdetection demo link](https://github.com/open-mmlab/mmdetection/tree/master/demo).

Thanks

**Comment by madhav1ag** [comment]
@Atul997 We have updated the demo folder for image_demo.py
