### ISSUE TITLE
single model CDeC-Net‡

### ISSUE THREAD

**Issue by ZF1546** [mdv3101/CDeCNet#6]
What is the difference between in single model CDeC-Net‡and CDeC-Net?
Can you provide the  pretrained models for single model CDeC-Net‡ in PubLayNet?
Thanks!

**Comment by madhav1ag** [comment]
Single model: It is trained on IIIT-AR-13k dataset and fine-tune on the training split of a given dataset.
Primary model: It is trained on the training split of a given dataset.

Generally, a model is trained for 50epochs. By using the pre-trained model on IIIT-AR-13k dataset, and fine tune it for 5-10epochs, we can achieve remarkably good results in much lesser time. Please go through the paper for more details.

We have provided the baseline pretrained model for single CDeC-Net‡. You can fine-tune it on PubLayNet. It won't be possible for us to release every pre-trained model file.

**Comment by ZF1546** [comment]
thank you very much!
