### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by ZF1546** [mdv3101/CDeCNet#7]
when I want to test model in image_demo.py that copy from 'mmdetection' ,report error 

RuntimeError: CUDA error: no kernel image is available for execution on the device (launch_kernel at /pytorch/aten/src/ATen/native/cuda/Loops.cuh:103)
frame # 0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fac76d7b193 in /home/wang388/346/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame # 1: void at::native::gpu_index_kernel<__nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> const&) + 0x7bb (0x7fabf16bc87b in /home/wang388/346/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame # 2: <unknown function> + 0x580fc32 (0x7fabf16b6c32 in /home/wang388/346/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame # 3: <unknown function> + 0x580ff88 (0x7fabf16b6f88 in /home/wang388/346/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame # 4: <unknown function> + 0x1a7493b (0x7fabed91b93b in /home/wang388/346/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame # 5: at::native::index(at::Tensor const&, c10::ArrayRef<at::Tensor>) + 0x47e (0x7fabed9176fe in /home/wang388/346/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame # 6: <unknown function> + 0x1fe06aa (0x7fabede876aa in /home/wang388/346/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame # 7: <unknown function> + 0x1fe5173 (0x7fabede8c173 in /home/wang388/346/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame # 8: <unknown function> + 0x3bffe6a (0x7fabefaa6e6a in /home/wang388/346/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame # 9: <unknown function> + 0x1fe5173 (0x7fabede8c173 in /home/wang388/346/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame # 10: at::Tensor::index(c10::ArrayRef<at::Tensor>) const + 0x191 (0x7fac7b99d921 in /home/wang388/346/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame # 11: nms_cuda_forward(at::Tensor, float) + 0x85f (0x7fac587fef1a in /home/wang388/346/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.0.0+e05e858-py3.7-linux-x86_64.egg/mmdet/ops/nms/nms_ext.cpython-37m-x86_64-linux-gnu.so)

the version of CUDA is 10.0.130
the version of pytorch is 1.4.0
the version of Torchvision is  0.5

thanks

**Comment by madhav1ag** [comment]
Can you give more information about your GPU card? There are few GPUs which are not supported. (refer to the following [link](https://github.com/pytorch/pytorch/issues/31285)). 
Our code is tested on RTX 2080Ti

**Comment by ZF1546** [comment]
The model  of my  GPU  Tesla V100 SXM2
I had train mask-rcnn model  in mmdtection .

**Comment by madhav1ag** [comment]
A similar issue was encountered by a user having Tesla V100 while using mmdetection. Please refer to the discussion and proposed solution from the following thread [link](https://github.com/open-mmlab/mmdetection/issues/3089#issuecomment-676764367).

**Comment by ZF1546** [comment]
ok! thank you very much!
