### ISSUE TITLE
Testing the model on IIIT-AR-13K - no detected tables.

### ISSUE THREAD

**Issue by syrinecheriaa** [mdv3101/CDeCNet#8]
I am interesting in using CDeCNet for detecting tables in annual reports. Thus, I tried to use your base model. I downloded the checkpoint that you shared (the file name is epoch_50.pth). After that I tried to use it with image from the dataset IIIT-AR-13K. I used mmdet.apis as suggested in the scrip [https://github.com/mdv3101/CDeCNet/blob/master/demo/image_demo.py](url). I used the config file [https://github.com/mdv3101/CDeCNet/blob/master/configs/cascade_rcnn/db_cascade_mask_rcnn_x101_32x4d_fpn_1x_coco.py](url). The script runs fine but no tables are detected ie the result returned by the command inference_detector(model, img) is empty. I am wondering if I am using the wrong checkpoint file or the wrong config. 
Thanks.

**Comment by syrinecheriaa** [comment]
It is clear that the checkpoint and the config file that I used do not match (there are some issues in the layers size). Could you please share the config file that match the base model?

**Comment by madhav1ag** [comment]
Hi @syrinecheriaa ,
Kindly use the following config file: 
configs/dcn/db_cascade_mask_rcnn_x101_fpn_dconv_c3-c5_1x_coco.py

**Comment by syrinecheriaa** [comment]
Thank you @mdv3101 .
