### ISSUE TITLE
RuntimeError: deform conv is not compiled with GPU support (deform_conv_forward at mmdet/ops/dcn/src/deform_conv_ext.cpp:63)

### ISSUE THREAD

**Issue by syrinecheriaa** [mdv3101/CDeCNet#9]
Hello, 
I am trying to use the base model trained on IIIT-AR-13K dataset. When executing the demo script, I face the error: RuntimeError: deform conv is not compiled with GPU support (deform_conv_forward at mmdet/ops/dcn/src/deform_conv_ext.cpp:63) which caused because the variable WITH_CUDA in the file deform_conv_ext.cpp is not defined. I can not manage to know where/how this variable is supposed to be defined. 
I installed all the packages with the required dependency except for cuda: torch.version.cuda is 10.1 and not 10.0. 
Could the faced error be caused by this versions mismatches? 
Thanks

**Comment by madhav1ag** [comment]
We highly recommend you to use the version specified.
